version: "3.9"

services:
  backend:
    image: metricmatters/famnav-backend:latest
    container_name: backend-container
    ports:
      - "8000:8000" # Map port 8000 for backend
    env_file:
      - ./backend/.env # Use the local .env file for backend
    depends_on:
      - frontend # Optional: Ensure frontend starts before backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: metricmatters/famnav-frontend:latest
    container_name: frontend-container
    ports:
      - "3000:3000" # Map port 3000 for frontend
    env_file:
      - ./frontend/.env # Use the local .env file for frontend
